# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\expedit\projects\crednexus\src\main\libcoin

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\expedit\projects\crednexus\src\main\libcoin

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"libcoin\" \"libcoin-dev\" \"libcoin-examples\" \"libcoin-tests\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake 2.8\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\expedit\projects\crednexus\src\main\libcoin\CMakeFiles E:\expedit\projects\crednexus\src\main\libcoin\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\expedit\projects\crednexus\src\main\libcoin\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles\uninstall.dir\build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named coin

# Build rule for target.
coin: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coin
.PHONY : coin

# fast build rule for target.
coin/fast:
	$(MAKE) -f src\coin\CMakeFiles\coin.dir\build.make src/coin/CMakeFiles/coin.dir/build
.PHONY : coin/fast

#=============================================================================
# Target rules for targets named coinChain

# Build rule for target.
coinChain: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coinChain
.PHONY : coinChain

# fast build rule for target.
coinChain/fast:
	$(MAKE) -f src\coinChain\CMakeFiles\coinChain.dir\build.make src/coinChain/CMakeFiles/coinChain.dir/build
.PHONY : coinChain/fast

#=============================================================================
# Target rules for targets named coinHTTP

# Build rule for target.
coinHTTP: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coinHTTP
.PHONY : coinHTTP

# fast build rule for target.
coinHTTP/fast:
	$(MAKE) -f src\coinHTTP\CMakeFiles\coinHTTP.dir\build.make src/coinHTTP/CMakeFiles/coinHTTP.dir/build
.PHONY : coinHTTP/fast

#=============================================================================
# Target rules for targets named coinNAT

# Build rule for target.
coinNAT: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coinNAT
.PHONY : coinNAT

# fast build rule for target.
coinNAT/fast:
	$(MAKE) -f src\coinNAT\CMakeFiles\coinNAT.dir\build.make src/coinNAT/CMakeFiles/coinNAT.dir/build
.PHONY : coinNAT/fast

#=============================================================================
# Target rules for targets named coinWallet

# Build rule for target.
coinWallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coinWallet
.PHONY : coinWallet

# fast build rule for target.
coinWallet/fast:
	$(MAKE) -f src\coinWallet\CMakeFiles\coinWallet.dir\build.make src/coinWallet/CMakeFiles/coinWallet.dir/build
.PHONY : coinWallet/fast

#=============================================================================
# Target rules for targets named coinPool

# Build rule for target.
coinPool: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 coinPool
.PHONY : coinPool

# fast build rule for target.
coinPool/fast:
	$(MAKE) -f src\coinPool\CMakeFiles\coinPool.dir\build.make src/coinPool/CMakeFiles/coinPool.dir/build
.PHONY : coinPool/fast

#=============================================================================
# Target rules for targets named app_libcoind

# Build rule for target.
app_libcoind: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 app_libcoind
.PHONY : app_libcoind

# fast build rule for target.
app_libcoind/fast:
	$(MAKE) -f applications\libcoind\CMakeFiles\app_libcoind.dir\build.make applications/libcoind/CMakeFiles/app_libcoind.dir/build
.PHONY : app_libcoind/fast

#=============================================================================
# Target rules for targets named app_coinexplorer

# Build rule for target.
app_coinexplorer: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 app_coinexplorer
.PHONY : app_coinexplorer

# fast build rule for target.
app_coinexplorer/fast:
	$(MAKE) -f applications\coinexplorer\CMakeFiles\app_coinexplorer.dir\build.make applications/coinexplorer/CMakeFiles/app_coinexplorer.dir/build
.PHONY : app_coinexplorer/fast

#=============================================================================
# Target rules for targets named app_cryptoshi

# Build rule for target.
app_cryptoshi: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 app_cryptoshi
.PHONY : app_cryptoshi

# fast build rule for target.
app_cryptoshi/fast:
	$(MAKE) -f applications\cryptoshi\CMakeFiles\app_cryptoshi.dir\build.make applications/cryptoshi/CMakeFiles/app_cryptoshi.dir/build
.PHONY : app_cryptoshi/fast

#=============================================================================
# Target rules for targets named example_simplecoin

# Build rule for target.
example_simplecoin: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 example_simplecoin
.PHONY : example_simplecoin

# fast build rule for target.
example_simplecoin/fast:
	$(MAKE) -f examples\simplecoin\CMakeFiles\example_simplecoin.dir\build.make examples/simplecoin/CMakeFiles/example_simplecoin.dir/build
.PHONY : example_simplecoin/fast

#=============================================================================
# Target rules for targets named example_ponzicoin

# Build rule for target.
example_ponzicoin: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 example_ponzicoin
.PHONY : example_ponzicoin

# fast build rule for target.
example_ponzicoin/fast:
	$(MAKE) -f examples\ponzicoin\CMakeFiles\example_ponzicoin.dir\build.make examples/ponzicoin/CMakeFiles/example_ponzicoin.dir/build
.PHONY : example_ponzicoin/fast

#=============================================================================
# Target rules for targets named example_extrawallet

# Build rule for target.
example_extrawallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 example_extrawallet
.PHONY : example_extrawallet

# fast build rule for target.
example_extrawallet/fast:
	$(MAKE) -f examples\extrawallet\CMakeFiles\example_extrawallet.dir\build.make examples/extrawallet/CMakeFiles/example_extrawallet.dir/build
.PHONY : example_extrawallet/fast

#=============================================================================
# Target rules for targets named test_blocktree

# Build rule for target.
test_blocktree: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_blocktree
.PHONY : test_blocktree

# fast build rule for target.
test_blocktree/fast:
	$(MAKE) -f tests\blocktree\CMakeFiles\test_blocktree.dir\build.make tests/blocktree/CMakeFiles/test_blocktree.dir/build
.PHONY : test_blocktree/fast

#=============================================================================
# Target rules for targets named test_claims

# Build rule for target.
test_claims: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_claims
.PHONY : test_claims

# fast build rule for target.
test_claims/fast:
	$(MAKE) -f tests\claims\CMakeFiles\test_claims.dir\build.make tests/claims/CMakeFiles/test_claims.dir/build
.PHONY : test_claims/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) -f tests\client\CMakeFiles\test_client.dir\build.make tests/client/CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

#=============================================================================
# Target rules for targets named test_extended_key

# Build rule for target.
test_extended_key: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_extended_key
.PHONY : test_extended_key

# fast build rule for target.
test_extended_key/fast:
	$(MAKE) -f tests\extended_key\CMakeFiles\test_extended_key.dir\build.make tests/extended_key/CMakeFiles/test_extended_key.dir/build
.PHONY : test_extended_key/fast

#=============================================================================
# Target rules for targets named test_jsonance

# Build rule for target.
test_jsonance: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_jsonance
.PHONY : test_jsonance

# fast build rule for target.
test_jsonance/fast:
	$(MAKE) -f tests\jsonance\CMakeFiles\test_jsonance.dir\build.make tests/jsonance/CMakeFiles/test_jsonance.dir/build
.PHONY : test_jsonance/fast

#=============================================================================
# Target rules for targets named test_merkletrie

# Build rule for target.
test_merkletrie: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_merkletrie
.PHONY : test_merkletrie

# fast build rule for target.
test_merkletrie/fast:
	$(MAKE) -f tests\merkletrie\CMakeFiles\test_merkletrie.dir\build.make tests/merkletrie/CMakeFiles/test_merkletrie.dir/build
.PHONY : test_merkletrie/fast

#=============================================================================
# Target rules for targets named test_namecoin

# Build rule for target.
test_namecoin: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_namecoin
.PHONY : test_namecoin

# fast build rule for target.
test_namecoin/fast:
	$(MAKE) -f tests\namecoin\CMakeFiles\test_namecoin.dir\build.make tests/namecoin/CMakeFiles/test_namecoin.dir/build
.PHONY : test_namecoin/fast

#=============================================================================
# Target rules for targets named test_sqliterate

# Build rule for target.
test_sqliterate: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 test_sqliterate
.PHONY : test_sqliterate

# fast build rule for target.
test_sqliterate/fast:
	$(MAKE) -f tests\sqliterate\CMakeFiles\test_sqliterate.dir\build.make tests/sqliterate/CMakeFiles/test_sqliterate.dir/build
.PHONY : test_sqliterate/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... coin
	@echo ... coinChain
	@echo ... coinHTTP
	@echo ... coinNAT
	@echo ... coinWallet
	@echo ... coinPool
	@echo ... app_libcoind
	@echo ... app_coinexplorer
	@echo ... app_cryptoshi
	@echo ... example_simplecoin
	@echo ... example_ponzicoin
	@echo ... example_extrawallet
	@echo ... test_blocktree
	@echo ... test_claims
	@echo ... test_client
	@echo ... test_extended_key
	@echo ... test_jsonance
	@echo ... test_merkletrie
	@echo ... test_namecoin
	@echo ... test_sqliterate
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

